# ---- Build Stage ----
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln ./
COPY EventBookingApp.API/*.csproj ./EventBookingApp.API/
COPY EventBookingApp.Application/*.csproj ./EventBookingApp.Application/
COPY EventBookingApp.Infrastructure/*.csproj ./EventBookingApp.Infrastructure/
COPY EventBookingApp.Domain/*.csproj ./EventBookingApp.Domain/

RUN dotnet restore

COPY . .
WORKDIR /src/EventBookingApp.API
RUN dotnet publish -c Release -o /app/publish

# ---- Runtime Stage ----
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:5128
EXPOSE 5128

ENTRYPOINT ["dotnet", "EventBookingApp.API.dll"]
