version: '3.8'

services:
  db:
    image: postgres:16
    container_name: eventbooking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventbooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventbooking-api
    ports:
      - "5128:5128"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=eventbooking;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    command: >
      sh -c "
      dotnet ef database update --project EventBookingApp.Infrastructure &&
      dotnet ef migrations add InitialCreate --project EventBookingApp.Infrastructure &&
      dotnet EventBookingApp.API.dll
      "

volumes:
  postgres_data:
